//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemoStart.Core.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars_BMW
    {
        public Cars_BMW()
        {
            this.Customer_BMW = new HashSet<Customer_BMW>();
        }
    
        public int ID { get; set; }
        public string Car_Name { get; set; }
        public string Engine_No { get; set; }
    
        public virtual ICollection<Customer_BMW> Customer_BMW { get; set; }
    }
}
