//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DemoStart.Core.Model;

namespace DemoStart.Infrastructure.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CustomerEntities : DbContext
    {
        public CustomerEntities()
            : base("name=CustomerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cars_BMW> Cars_BMW { get; set; }
        public DbSet<Customer_BMW> Customer_BMW { get; set; }
        public DbSet<tbldemo> tbldemoes { get; set; }
        public DbSet<tbldemo2> tbldemo2 { get; set; }
        public DbSet<NLog_Error> NLog_Error { get; set; }
    }
}
